### ISSUE TITLE
Too loud!

### ISSUE THREAD

**Issue by rezogo** [lazy-guy/tomodoro#1]
Really like it but the sound is too loud! When you return to it from YT, your media etc you can go deaf so loud is the white noise. Could you please address this issue?

**Comment by Weizhe-Chen** [comment]
Hello @rezogo,
I've incorporated the requested functionality in my pull request. Prior to having @lazy-guy merge the changes, you have the option to temporarily use my fork at https://github.com/Weizhe-Chen/tomodoro. It's hosted on this website: https://wchen-robotics.com/tomodoro/

**Comment by rezogo** [comment]
Fantastic! Thank you

**Comment by lazy-guy** [comment]
I have merged the changes done by @Weizhe-Chen (#7), which adds a volume slider for controlling the loudness.
