### ISSUE TITLE
White noise UX glitches

### ISSUE THREAD

**Issue by polettix** [lazy-guy/tomodoro#10]
Tried this in Firefox 124.0.1 (64 bit) in Windows 11 Home edition.

I was curious about white noise so I wanted to give it a try:

- The main window shows the volume slider, I tried to use it without success. Only later I discovered that it was disabled while looking at the other options for configuration. My suggestion is to make it explicit whether white noise is active or not in the main window.
- Enabling white noise does not work *on the spot*. I had to restart the task to hear it. After that it worked, although I went to the configuration panel, disable it, apply (no sound, OK) then re-enable it, apply (still no sound, NOT OK I daresay).

I'm not really planning on using white noise, but I thought it would be good for you to know my counter-intuitive UX!

Cheers and congratulations for such a clean tool.

**Comment by lazy-guy** [comment]
The latest commits have (hopefully) fixed the white noise related issues.

- The volume slider should be functional now. It used to look somewhat out of place, so it has been redesigned to blend in with other UI elements.
- White noise should start working immediately, without having to restart the task.
