### ISSUE TITLE
Daily log suggestion

### ISSUE THREAD

**Issue by rednatnas** [lazy-guy/tomodoro#3]
It would be good if, in the statistics tab, there was an option to see the hours spent today, not just the previous day. It would be really useful.

**Comment by Weizhe-Chen** [comment]
Hi @rednatnas ,
I have added the functionality you requested in my pull request. Before @lazy-guy merge the pull request, you can temporarily use my fork https://github.com/Weizhe-Chen/tomodoro which is hosted on this website: https://wchen-robotics.com/tomodoro/

**Comment by lazy-guy** [comment]
I have merged the changes done by @Weizhe-Chen (#7), which adds this functionality.
